### PR TITLE
fix: dispatch returns undefined value

### LINKED ISSUE #82: makeEnhancer from @redux-tools/middleware invalidate action returns - it always returns undefined
If I have a middleware which turns my dispatched actions into promises, I want to be able to get that promise back dispatching action eg.:
`const promise = dispatch(action())`
but because of makeEnhancer from @redux-tools/middleware, it always returns undefined instead of promise.

### PR DESCRIPTION
**Pull request by dunaevskiy**
resolves #82

### CODE REVIEW

**Comment by jsifalda** [comment]
I dont think this is really the fix of the problem, because I tried to put return there in my local clone and it didnt work...

**Comment by wafflepie** [comment]
there are tests which verify that this is working.

there might also be a problem in any of the middleware you are using yourself, because you need to make sure that you return always return the action

**Comment by jsifalda** [comment]
even tests can have bugs :D I can try again I guess, but I am sure it had nothing to do with my other middleware because I didnt any other. Plus I tried specifically disable this middleware and was working again.

**Comment by wafflepie** [comment]
we are going to add one more test to verify that multiple middleware will not break as well

however, the return value of dispatch should actually be equal to the return value of outermost middleware injected (either the first middleware in applyMiddleware or the first injected middleware)

**Comment by wafflepie** [comment]
i had a closer look and we actually can't do much more than this, it would differ from the implementation used in `applyMiddleware` of Redux

**Comment by jsifalda** [comment]
lets merge it then 😉

**Comment by wafflepie** [comment]
love it, thanks!

**Comment by jsifalda** [comment]
Will you do minor npm version with this? Please

**Pull request merged**
